### PR TITLE
Build system

### PR DESCRIPTION
**Pull request by Trippnology**
# Build system

Two packages have been installed to help with the build process; [modclean](https://github.com/ModClean/modclean) and [electron-builder](https://github.com/electron-userland/electron-builder). Modclean strips out superfluous files from the `node_modules` directory in order to shrink the final size of the release files, while electron-builder helps to create the release files for the various platforms.

There are MANY configuration options available for electron-builder (set in the `build` section of `package.json`). A good overview can be found [here](https://www.electron.build/configuration/configuration), along with specific info about [Windows](https://www.electron.build/configuration/win), [Mac](https://www.electron.build/configuration/mac), and [Linux](https://www.electron.build/configuration/linux) options. You will need to add some Mac options yourself (at least `"target"=["default"]`) in order to test, as building for Mac is only available _on_ Mac.

NPM scripts have been added to run these 2 tasks (use with `npm run trim_modules` and `npm run dist`), along with a further task (`postversion`) that will run both, after creating a new version.

It's a good idea to do `rm -rf node_modules/ && npm i` before you start, so you have a completely up to date `node_modules/` dir, just like a new user would see.

If you decide you want to commit the binaries to the repo (not sure if this is a good idea or not), the `postversion` script should be modified to be a `version` script instead:

```json
// Current script runs AFTER creating the version auto commit
// and does NOT include the binaries produced:
"postversion": "npm run trim_modules && npm run dist"
// To include the binaries in the repo, modify to be a version script instead,
// and add the resulting files to the index before the version auto commit:
"version": "npm run trim_modules && npm run dist && git add -A ."
```

## Windows installer formats

I tried both the default NSIS installer, and the MSI installer. The NSIS was much faster to both build and install, so I suggest sticking with that.

## Output files

The current settings produce 3 files for Windows:

-   `JS8Assistant <version>.exe` - This is a "portable" file, meaning it takes a few seconds longer to load, but is a single file, and needs no installation. Approx 52MB
-   `JS8Assistant Setup <version>.exe` - This is the NSIS installer, that most users would probably want. Allows choice of install dir, adds desktop icon, uninstaller, all that jazz. Approx 52MB
-   `JS8Assistant-<version>-win.zip` - No installer, just a compressed file with everything you need. Extract and run the `JS8Assistant.exe` file within. Approx 80MB

On my machine, the build process takes around 1m 05s and I guess Mac and Linux would each take a similar time.

Let's get the Mac build working before trying Linux.

### CODE REVIEW

**Comment by RocketManRC** [comment]
This is great! I've added the DMG target for MacOS which is good enough and it builds and runs fine.

For Linux I think that DEB files should do the job with one for X86 and one for ARM (Raspberry Pi).

**Comment by Trippnology** [comment]
Nice one, glad that's working well.

I should point out that this setup is only building for 64bit Windows. I did try adding 32bit too, but this doubles the size of the installer, as both versions are included in one file. 

I can't imagine there would be much demand, but if someone really wanted to build for 32bit Windows (primarily XP), they would just need to add `"ia32"` to the NSIS target arch list:

```json
{
    "target": "nsis",
    "arch": [
        "x64",
        "ia32"
    ]
},
```

... and run `npm run dist` to start the build process.

**Comment by RocketManRC** [comment]
I don't think there will be any demand for Win32 but I will be sure to make a note about that.

After some investigation today it seems that there are issues with electron-builder making Linux binaries that will run out of the box due to the fact that file chrome-sandbox has the wrong permissions. I am trying to come up with a good solution for that but I haven't been successful so far.

**Comment by RocketManRC** [comment]
Added support for building deb files for Debian Linux and Raspberry Pi. For the Raspi some hocus pocus is needed as described here: https://www.beekeeperstudio.io/blog/electron-apps-for-arm-and-raspberry-pi.

Will merge the pull request now and post the binaries in Releases as version 0.21.2.

**Pull request merged**
